# Write your MySQL query statement beloW
SELECT S.STUDENT_ID, S.STUDENT_NAME, SU.SUBJECT_NAME, COUNT(E.STUDENT_ID) AS ATTENDED_EXAMS
FROM STUDENTS S
CROSS JOIN SUBJECTS SU
LEFT JOIN EXAMINATIONS E
ON E.STUDENT_ID = S.STUDENT_ID
AND E.SUBJECT_NAME = SU.SUBJECT_NAME
GROUP BY S.STUDENT_ID, S.STUDENT_NAME, SU.SUBJECT_NAME
ORDER BY S.STUDENT_ID, S.STUDENT_NAME, SU.SUBJECT_NAME
