# Write your MySQL query statement below
SELECT CUSTOMER_ID, COUNT(VISITS.VISIT_ID) AS COUNT_NO_TRANS
FROM VISITS
LEFT JOIN TRANSACTIONS
ON TRANSACTIONS.VISIT_ID = VISITS.VISIT_ID
WHERE TRANSACTIONS.VISIT_ID IS NULL 
GROUP BY CUSTOMER_ID
